import {
  albumsOutline,
  appsOutline,
  bagHandleOutline,
  bookOutline,
  briefcaseOutline,
  cardOutline,
  cashOutline,
  cloudOutline,
  codeSlashOutline,
  cubeOutline,
  filmOutline,
  fitnessOutline,
  gameControllerOutline,
  globeOutline,
  heartOutline,
  homeOutline,
  logoApple,
  logoFigma,
  logoGoogle,
  logoYoutube,
  mailOutline,
  musicalNotesOutline,
  newspaperOutline,
  phonePortraitOutline,
  planetOutline,
  playCircleOutline,
  radioOutline,
  restaurantOutline,
  schoolOutline,
  serverOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  starOutline,
  tvOutline,
  walletOutline,
  wifiOutline
} from "ionicons/icons";

export type PickerMode = "icon" | "color";

export const iconOptions = [
  {id: "youtube", label: "YouTube", icon: logoYoutube},
  {id: "apple", label: "Apple", icon: logoApple},
  {id: "google", label: "Google", icon: logoGoogle},
  {id: "figma", label: "Figma", icon: logoFigma},
  {id: "video", label: "Видео", icon: playCircleOutline},
  {id: "tv", label: "ТВ", icon: tvOutline},
  {id: "film", label: "Кино", icon: filmOutline},
  {id: "music", label: "Музыка", icon: musicalNotesOutline},
  {id: "radio", label: "Радио", icon: radioOutline},
  {id: "cloud", label: "Облако", icon: cloudOutline},
  {id: "server", label: "Сервер", icon: serverOutline},
  {id: "code", label: "Код", icon: codeSlashOutline},
  {id: "wallet", label: "Кошелек", icon: walletOutline},
  {id: "card", label: "Карта", icon: cardOutline},
  {id: "cash", label: "Деньги", icon: cashOutline},
  {id: "game", label: "Игры", icon: gameControllerOutline},
  {id: "book", label: "Книги", icon: bookOutline},
  {id: "school", label: "Учеба", icon: schoolOutline},
  {id: "news", label: "Новости", icon: newspaperOutline},
  {id: "fitness", label: "Спорт", icon: fitnessOutline},
  {id: "food", label: "Еда", icon: restaurantOutline},
  {id: "shopping", label: "Покупки", icon: bagHandleOutline},
  {id: "work", label: "Работа", icon: briefcaseOutline},
  {id: "phone", label: "Связь", icon: phonePortraitOutline},
  {id: "wifi", label: "Интернет", icon: wifiOutline},
  {id: "mail", label: "Почта", icon: mailOutline},
  {id: "security", label: "Защита", icon: shieldCheckmarkOutline},
  {id: "home", label: "Дом", icon: homeOutline},
  {id: "health", label: "Здоровье", icon: heartOutline},
  {id: "world", label: "Мир", icon: globeOutline},
  {id: "creative", label: "Творчество", icon: sparklesOutline},
  {id: "premium", label: "Премиум", icon: starOutline},
  {id: "space", label: "Космос", icon: planetOutline},
  {id: "archive", label: "Коллекция", icon: albumsOutline},
  {id: "service", label: "Сервис", icon: cubeOutline},
  {id: "other", label: "Другое", icon: appsOutline}
];

export const colorOptions = [
  {id: "green", label: "Зеленый"},
  {id: "blue", label: "Синий"},
  {id: "violet", label: "Фиолетовый"},
  {id: "orange", label: "Оранжевый"},
  {id: "red", label: "Красный"},
  {id: "cyan", label: "Голубой"},
  {id: "pink", label: "Розовый"},
  {id: "amber", label: "Янтарный"},
  {id: "indigo", label: "Индиго"},
  {id: "slate", label: "Графит"}
];
